=== stephen1590/DayZSuite/ConfigViewer/tools/loadout.schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/LoadoutSchema",
    "definitions": {
        "Health": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "Min": {
                    "type": "number"
                },
                "Max": {
                    "type": "integer"
                },
                "Zone": {
                    "type": "string"
                }
            },
            "required": [
                "Max",
                "Min",
                "Zone"
            ],
            "title": "Health"
        },
        "InventoryAttachment": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "SlotName": {
                    "type": "string"
                },
                "Items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LoadoutSchema"
                    }
                }
            },
            "required": [
                "Items",
                "SlotName"
            ],
            "title": "InventoryAttachment"
        },
        "LoadoutSchema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "ClassName": {
                    "type": "string"
                },
                "Include": {
                    "type": "string"
                },
                "Chance": {
                    "type": "number"
                },
                "Quantity": {
                    "$ref": "#/definitions/Quantity"
                },
                "Health": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Health"
                    }
                },
                "InventoryAttachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/InventoryAttachment"
                    }
                },
                "InventoryCargo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LoadoutSchema"
                    }
                },
                "ConstructionPartsBuilt": {
                    "type": "array",
                    "items": {}
                },
                "Sets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LoadoutSchema"
                    }
                }
            },
            "required": [
                "Chance",
                "ClassName",
                "ConstructionPartsBuilt",
                "Health",
                "Include",
                "InventoryAttachments",
                "InventoryCargo",
                "Quantity",
                "Sets"
            ],
            "title": "LoadoutSchema"
        },
        "Quantity": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "Min": {
                    "type": "number"
                },
                "Max": {
                    "type": "number"
                }
            },
            "required": [
                "Max",
                "Min"
            ],
            "title": "Quantity"
        }
    }
}

=== stephen1590/DayZSuite/config-defaults/profiles/ExpansionMod/Loadouts/SurvivorLoadout.defaults.json
{
    "ClassName": "",
    "Include": "",
    "Chance": 1.0,
    "Quantity": {
        "Min": 0.0,
        "Max": 0.0
    },
    "Health": [],
    "InventoryAttachments": [
        {
            "SlotName": "Body",
            "Items": [
                {
                    "ClassName": "GorkaEJacket_Autumn",
                    "Include": "",
                    "Chance": 1.0,
                    "Quantity": {
                        "Min": 0.0,
                        "Max": 0.0
                    },
                    "Health": [
                        {
                            "Min": 0.699999988079071,
                            "Max": 1.0,
                            "Zone": ""
                        }
                    ],
                    "InventoryAttachments": [],
                    "InventoryCargo": [],
                    "ConstructionPartsBuilt": [],
                    "Sets": []
                },
                {
                    "ClassName": "GorkaEJacket_Flat",
                    "Include": "",
                    "Chance": 1.0,
                    "Quantity": {
                        "Min": 0.0,
                        "Max": 0.0
                    },
                    "Health": [
                        {
                            "Min": 0.699999988079071,
                            "Max": 1.0,
                            "Zone": ""
                        }
                    ],
                    "InventoryAttachments": [],
                    "InventoryCargo": [],
                    "ConstructionPartsBuilt": [],
                    "Sets": []
                },
                {
                    "ClassName": "GorkaEJacket_PautRev",
                    "Include": "",
                    "Chance": 1.0,
                    "Quantity": {
                        "Min": 0.0,
                        "Max": 0.0
                    },
                    "Health": [
                        {
                            "Min": 0.699999988079071,
                            "Max": 1.0,
                            "Zone": ""
                        }
                    ],
                    "InventoryAttachments": [],
                    "InventoryCargo": [],
                    "ConstructionPartsBuilt": [],
                    "Sets": []
                },
                {
                    "ClassName": "GorkaEJacket_Summer",
                    "Include": "",
                    "Chance": 1.0,
                    "Quantity": {
                        "Min": 0.0,
                        "Max": 0.0
                    },
                    "Health": [
                        {
                            "Min": 0.699999988079071,
                            "Max": 1.0,
                            "Zone": ""
                        }
                    ],
                    "InventoryAttachments": [],
                    "InventoryCargo": [],
                    "ConstructionPartsBuilt": [],
                    "Sets": []
                },
                {
                    "ClassName": "TTsKOJacket_Camo",
                    "Include": "",
                    "Chance": 1.0,
                    "Quantity": {
                        "Min": 0.0,
                        "Max": 0.0
                    },
                    "Health": [
                        {
                            "Min": 0.699999988079071,
                            "Max": 1.0,
                            "Zone": ""
                        }
                    ],
                    "InventoryAttachments": [],
                    "InventoryCargo": [],
                    "ConstructionPartsBuilt": [],
                    "Sets": []
                },
                {
                    "ClassName": "Hoodie_Black",
                    "Include": "",
                    "Chance": 1.0,
                    "Quantity": {
                        "Min": 0.0,
                        "Max": 0.0
                    },
                    "Health": [
                        {
                            "Min": 0.699999988079071,
                            "Max": 1.0,
                            "Zone": ""
                        }
                    ],
                    "InventoryAttachments": [],
                    "InventoryCargo": [],
                    "ConstructionPartsBuilt": [],
                    "Sets": []
                },
                {
                    "ClassName": "Hoodie_Blue",
                    "Include": "",
                    "Chance": 1.0,
                    "Quantity": {
                        "Min": 0.0,
                        "Max": 0.0
                    },
                    "Health": [
                        {
                            "Min": 0.699999988079071,
                            "Max": 1.0,
                            "Zone": ""
                        }
                    ],
                    "InventoryAttachments": [],
                    "InventoryCargo": [],
                    "ConstructionPartsBuilt": [],
                    "Sets": []
                },
                {
                    "ClassName": "Hoodie_Brown",
                    "Include": "",
                    "Chance": 1.0,
                    "Quantity": {
                        "Min": 0.0,
                        "Max": 0.0
                    },
                    "Health": [
                        {
                            "Min": 0.699999988079071,
                            "Max": 1.0,
                            "Zone": ""
                        }
                    ],
                    "InventoryAttachments": [],
                    "InventoryCargo": [],
                    "ConstructionPartsBuilt": [],
                    "Sets": []
                },
                {
                    "ClassName": "Hoodie_Green",
                    "Include": "",
                    "Chance": 1.0,
                    "Quantity": {
                        "Min": 0.0,
                        "Max": 0.0
                    },
                    "Health": [
                        {
                            "Min": 0.699999988079071,
                            "Max": 1.0,
                            "Zone": ""
                        }
                    ],
                    "InventoryAttachments": [],
                    "InventoryCargo": [],
                    "ConstructionPartsBuilt": [],
                    "Sets": []
                },
                {
                    "ClassName": "Hoodie_Grey",
                    "Include": "",
                    "Chance": 1.0,
                    "Quantity": {
                        "Min": 0.0,
                        "Max": 0.0
                    },
                    "Health": [
                        {
                            "Min": 0.699999988079071,
                            "Max": 1.0,
                            "Zone": ""
                        }
                    ],
                    "InventoryAttachments": [],
                    "InventoryCargo": [],
                    "ConstructionPartsBuilt": [],
                    "Sets": []
                },
                {
                    "ClassName": "Hoodie_Red",
                    "Include": "",
                    "Chance": 1.0,
                    "Quantity": {
                        "Min": 0.0,
                        "Max": 0.0
                    },
                    "Health": [
                        {
                            "Min": 0.699999988079071,
                            "Max": 1.0,
                            "Zone": ""
                        }
                    ],
                    "InventoryAttachments": [],
                    "InventoryCargo": [],
                    "ConstructionPartsBuilt": [],
                    "Sets": []
                },
                {
                    "ClassName": "BomberJacket_Black",
                    "Include": "",
                    "Chance": 1.0,
                    "Quantity": {
                        "Min": 0.0,
                        "Max": 0.0
                    },
                    "Health": [
                        {
                            "Min": 0.699999988079071,
                            "Max": 1.0,
                            "Zone": ""
                        }
                    ],
                    "InventoryAttachments": [],
                    "InventoryCargo": [],
                    "ConstructionPartsBuilt": [],
                    "Sets": []
                },
                {
                    "ClassName": "BomberJacket_Blue",
                    "Include": "",
                    "Chance": 1.0,
                    "Quantity": {
                        "Min": 0.0,
                        "Max": 0.0
                    },
                    "Health": [
                        {
                            "Min": 0.699999988079071,
                            "Max": 1.0,
                            "Zone": ""
                        }
                    ],
                    "InventoryAttachments": [],
                    "InventoryCargo": [],
                    "ConstructionPartsBuilt": [],
                    "Sets": []
                },
                {
                    "ClassName": "BomberJacket_Brown",
                    "Include": "",
                    "Chance": 1.0,
                    "Quantity": {
                        "Min": 0.0,
                        "Max": 0.0
                    },
                    "Health": [
                        {
                            "Min": 0.699999988079071,
                            "Max": 1.0,
                            "Zone": ""
                        }
                    ],
                    "InventoryAttachments": [],
                    "InventoryCargo": [],
                    "ConstructionPartsBuilt": [],
                    "Sets": []
